{% set name = "opendp-smartnoise" %}
{% set version = "0.1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/opendp-smartnoise-{{ version }}.tar.gz
  sha256: 37b98a777663d4c49837c5f03997f0c0c2503892ecb00766ba7d49ff6605ce3e
  patches:
    - 0001-fixed-imports.patch

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - antlr4-python3-runtime
    - msrest
    - numpy
    - opendp-smartnoise-core
    - pandas
    - pandasql
    - python >={{ python_min }}
    - pyyaml
    - scipy
    - statsmodels

test:
  imports:
    - opendp.smartnoise
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/opendp-smartnoise/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'SmartNoise: Tools for Differential Privacy'

extra:
  recipe-maintainers:
    - d-cunningham
    - oblute
    - mxr-conda

